// Basic commands
export const SCD4X_CMD_START_PERIODIC_MEASUREMENT = 0x21b1;
export const SCD4X_CMD_READ_MEASUREMENT = 0xec05;
export const SCD4X_CMD_STOP_PERIODIC_MEASUREMENT = 0x3f86;

// On-chip output signal compensation
export const SCD4X_CMD_SET_TEMPERATURE_OFFSET = 0x241d;
export const SCD4X_CMD_GET_TEMPERATURE_OFFSET = 0x2318;
export const SCD4X_CMD_SET_SENSOR_ALTITUDE = 0x2427;
export const SCD4X_CMD_GET_SENSOR_ALTITUDE = 0x2322;
export const SCD4X_CMD_SET_AMBIENT_PRESSURE = 0xe000;

// Field calibration
export const SCD4X_CMD_PERFORM_FORCED_RECALIBRATION = 0x362f;
export const SCD4X_CMD_SET_AUTO_SELF_CALIBRATION = 0x2416;
export const SCD4X_CMD_GET_AUTO_SELF_CALIBRATION = 0x2313;

// Low power
export const SCD4X_CMD_START_LOW_POWER_PERIODIC_MEASUREMENT = 0x21ac;
export const SCD4X_CMD_GET_DATA_READY_STATUS = 0xe4b8;

// Advanced features
export const SCD4X_CMD_PERSIST_SETTINGS = 0x3615;
export const SCD4X_CMD_GET_SERIAL_NUMBER = 0x3682;
export const SCD4X_CMD_PERFORM_SELF_TEST = 0x3639;
export const SCD4X_CMD_PERFORM_FACTORY_RESET = 0x3632;
export const SCD4X_CMD_REINIT = 0x3646;

// Low power single shot
export const SCD4X_CMD_MEASURE_SINGLE_SHOT = 0x219d;
export const SCD4X_CMD_MEASURE_SINGLE_SHOT_RHT_ONLY = 0x2196;

export const SCD4X_ADDRESS = 0x62;
